quarkus.http.test-port=0

quarkus.log.category."io.quarkiverse.langfuse".level=DEBUG

quarkus.langfuse.devservices.enabled=false
quarkus.langfuse.base-url=http://localhost:3000
quarkus.langfuse.public-key=pk-lf-test
quarkus.langfuse.secret-key=sk-lf-test
